version: "2.18"
services:
  api:
    build: ./api
    container_name: api_node
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  react-app:
    build: ./myblog
    container_name: myblog
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
